#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: $(basename $0) pathstring searchstring header"
    echo "Finds all jars under the current dir whose path matches 'pathstring' and searches their manifests for 'searchstring' in the given 'header'."
    echo
    echo "Example: $(basename $0) target/application org.apache.http Import-Package"
    exit 1
fi

PATHSTRING=$1
SEARCH=$2
HEADER=$3
ROOTDIR="."

echo "Searching jars with path matching $PATHSTRING for '$SEARCH' in header $HEADER"

matches=""
cnt=0
match_cnt=0
for jar in `find $ROOTDIR -name "*.jar" | grep $PATHSTRING`; do
    ((cnt++))
    echo --- ${jar#"$ROOTDIR/"} ---
    bnd select -h $HEADER $jar | grep $SEARCH && matches=$(printf "$matches\n$jar") && ((match_cnt++))
done

sorted=$(echo $matches | xargs -n1 | sort | xargs | tr ' ' '\n')

printf '\n%s' "Searched $cnt bundles and found $match_cnt matches"
printf '\n%s' "Jars matching '$SEARCH' in '$HEADER':"
printf '\n%s\n' "$sorted"
